# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AudioPlayer.ui'
#
# Created: Tue Nov 25 16:01:52 2014
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AudioPlayer(object):
    def setupUi(self, AudioPlayer):
        AudioPlayer.setObjectName(_fromUtf8("AudioPlayer"))
        AudioPlayer.setEnabled(True)
        AudioPlayer.resize(400, 400)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AudioPlayer.sizePolicy().hasHeightForWidth())
        AudioPlayer.setSizePolicy(sizePolicy)
        AudioPlayer.setMinimumSize(QtCore.QSize(400, 400))
        AudioPlayer.setMaximumSize(QtCore.QSize(400, 400))
        self.centralwidget = QtGui.QWidget(AudioPlayer)
        self.centralwidget.setMinimumSize(QtCore.QSize(400, 400))
        self.centralwidget.setMaximumSize(QtCore.QSize(400, 400))
        self.centralwidget.setStyleSheet(_fromUtf8(""))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 401, 401))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widget = QtGui.QWidget(self.verticalLayoutWidget)
        self.widget.setStyleSheet(_fromUtf8(""))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.widget_3 = QtGui.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(0, 260, 400, 141))
        self.widget_3.setStyleSheet(_fromUtf8("border-image: url(:/icons/1.png);"))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.musicName = QtGui.QLabel(self.widget_3)
        self.musicName.setGeometry(QtCore.QRect(0, 235, 399, 30))
        self.musicName.setMinimumSize(QtCore.QSize(0, 0))
        self.musicName.setMaximumSize(QtCore.QSize(16777215, 30))
        self.musicName.setText(_fromUtf8(""))
        self.musicName.setAlignment(QtCore.Qt.AlignCenter)
        self.musicName.setObjectName(_fromUtf8("musicName"))
        self.playButton = QtGui.QPushButton(self.widget_3)
        self.playButton.setGeometry(QtCore.QRect(130, 40, 48, 48))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playButton.sizePolicy().hasHeightForWidth())
        self.playButton.setSizePolicy(sizePolicy)
        self.playButton.setMinimumSize(QtCore.QSize(40, 40))
        self.playButton.setStyleSheet(_fromUtf8("border-image: url(:/icons/play.png);"))
        self.playButton.setText(_fromUtf8(""))
        self.playButton.setIconSize(QtCore.QSize(40, 40))
        self.playButton.setObjectName(_fromUtf8("playButton"))
        self.stopButton = QtGui.QPushButton(self.widget_3)
        self.stopButton.setGeometry(QtCore.QRect(200, 40, 50, 50))
        self.stopButton.setStyleSheet(_fromUtf8("border-image: url(:/icons/stop.png);"))
        self.stopButton.setText(_fromUtf8(""))
        self.stopButton.setIconSize(QtCore.QSize(30, 30))
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.volumeSlider = phonon.Phonon.VolumeSlider(self.widget_3)
        self.volumeSlider.setGeometry(QtCore.QRect(270, 100, 114, 36))
        self.volumeSlider.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.volumeSlider.setAutoFillBackground(False)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName(_fromUtf8("volumeSlider"))
        self.lyric = QtGui.QPushButton(self.widget_3)
        self.lyric.setGeometry(QtCore.QRect(40, 111, 17, 17))
        self.lyric.setStyleSheet(_fromUtf8("border-image: url(:/icons/lyric_on.png);"))
        self.lyric.setText(_fromUtf8(""))
        self.lyric.setObjectName(_fromUtf8("lyric"))
        self.albumAndSinger = QtGui.QLabel(self.widget_3)
        self.albumAndSinger.setGeometry(QtCore.QRect(0, 266, 399, 30))
        self.albumAndSinger.setMaximumSize(QtCore.QSize(16777215, 30))
        self.albumAndSinger.setText(_fromUtf8(""))
        self.albumAndSinger.setAlignment(QtCore.Qt.AlignCenter)
        self.albumAndSinger.setObjectName(_fromUtf8("albumAndSinger"))
        self.prevButton = QtGui.QPushButton(self.widget_3)
        self.prevButton.setGeometry(QtCore.QRect(60, 40, 50, 50))
        self.prevButton.setStyleSheet(_fromUtf8("border-image: url(:/icons/prev.png);"))
        self.prevButton.setText(_fromUtf8(""))
        self.prevButton.setObjectName(_fromUtf8("prevButton"))
        self.nextButton = QtGui.QPushButton(self.widget_3)
        self.nextButton.setGeometry(QtCore.QRect(270, 40, 50, 50))
        self.nextButton.setStyleSheet(_fromUtf8("border-image: url(:/icons/next.png);"))
        self.nextButton.setText(_fromUtf8(""))
        self.nextButton.setObjectName(_fromUtf8("nextButton"))
        self.timeLcd = QtGui.QLCDNumber(self.widget_3)
        self.timeLcd.setGeometry(QtCore.QRect(330, 0, 64, 32))
        self.timeLcd.setStyleSheet(_fromUtf8("border-image: url(:/icons/1.png);"))
        self.timeLcd.setObjectName(_fromUtf8("timeLcd"))
        self.list = QtGui.QPushButton(self.widget_3)
        self.list.setGeometry(QtCore.QRect(10, 111, 17, 17))
        self.list.setStyleSheet(_fromUtf8("border-image: url(:/icons/list_off.png);"))
        self.list.setText(_fromUtf8(""))
        self.list.setObjectName(_fromUtf8("list"))
        self.seekSlider = phonon.Phonon.SeekSlider(self.widget_3)
        self.seekSlider.setGeometry(QtCore.QRect(0, 0, 327, 32))
        self.seekSlider.setMaximumSize(QtCore.QSize(16777215, 40))
        self.seekSlider.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.seekSlider.setStyleSheet(_fromUtf8(""))
        self.seekSlider.setObjectName(_fromUtf8("seekSlider"))
        self.widget_2 = QtGui.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 400, 261))
        self.widget_2.setStyleSheet(_fromUtf8("border-image: url(:/icons/background.png);"))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.nextLyric = QtGui.QLabel(self.widget_2)
        self.nextLyric.setGeometry(QtCore.QRect(0, 160, 400, 21))
        self.nextLyric.setStyleSheet(_fromUtf8("border-image: transparent"))
        self.nextLyric.setText(_fromUtf8(""))
        self.nextLyric.setAlignment(QtCore.Qt.AlignCenter)
        self.nextLyric.setObjectName(_fromUtf8("nextLyric"))
        self.currentLyric = QtGui.QLabel(self.widget_2)
        self.currentLyric.setGeometry(QtCore.QRect(0, 130, 400, 21))
        self.currentLyric.setStyleSheet(_fromUtf8("border-image: transparent"))
        self.currentLyric.setText(_fromUtf8(""))
        self.currentLyric.setAlignment(QtCore.Qt.AlignCenter)
        self.currentLyric.setObjectName(_fromUtf8("currentLyric"))
        self.closeButton = QtGui.QPushButton(self.widget_2)
        self.closeButton.setGeometry(QtCore.QRect(40, 0, 16, 21))
        self.closeButton.setStyleSheet(_fromUtf8("border-image: url(:/icons/close.png);"))
        self.closeButton.setText(_fromUtf8(""))
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.minimizeButton = QtGui.QPushButton(self.widget_2)
        self.minimizeButton.setGeometry(QtCore.QRect(0, 0, 31, 20))
        self.minimizeButton.setStyleSheet(_fromUtf8("border-image: url(:/icons/minimize.png);"))
        self.minimizeButton.setText(_fromUtf8(""))
        self.minimizeButton.setObjectName(_fromUtf8("minimizeButton"))
        self.verticalLayout.addWidget(self.widget)
        AudioPlayer.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(AudioPlayer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBar.sizePolicy().hasHeightForWidth())
        self.statusBar.setSizePolicy(sizePolicy)
        self.statusBar.setBaseSize(QtCore.QSize(400, 23))
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        AudioPlayer.setStatusBar(self.statusBar)

        self.retranslateUi(AudioPlayer)
        QtCore.QMetaObject.connectSlotsByName(AudioPlayer)

    def retranslateUi(self, AudioPlayer):
        AudioPlayer.setWindowTitle(_translate("AudioPlayer", "MainWindow", None))
        self.playButton.setStatusTip(_translate("AudioPlayer", "播放", None))
        self.stopButton.setStatusTip(_translate("AudioPlayer", "停止", None))
        self.volumeSlider.setStatusTip(_translate("AudioPlayer", "音量", None))
        self.lyric.setStatusTip(_translate("AudioPlayer", "隐藏歌词", None))
        self.prevButton.setStatusTip(_translate("AudioPlayer", "上一首", None))
        self.nextButton.setStatusTip(_translate("AudioPlayer", "下一首", None))
        self.list.setStatusTip(_translate("AudioPlayer", "播放列表", None))
        self.closeButton.setStatusTip(_translate("AudioPlayer", "关闭", None))
        self.minimizeButton.setStatusTip(_translate("AudioPlayer", "最小化", None))

from PyQt4 import phonon
import buttonIcon_rc
